sudo: false
language: python
cache:
  directories:
    - $HOME/.cache/pip
addons:
  apt:
    sources:
    - kalakris-cmake
    packages:
    - cmake
    - check
    - fftw3
    - libfftw3-dev
    - cython
    - python-numpy
    - python-cython
    - python-dev

install:
  # Hack so python bindings can find locally installed library file
  - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/libswiftnav/build/install/usr/local/lib
  - git submodule update --init

script:
  # Build libswiftnav
  - cd libswiftnav/
  - mkdir build
  - cd build/
  - cmake ../
  - make
  # Install locally to avoid sudo
  - make DESTDIR="./install" install
  - cd ../python
  - pip install -r requirements.txt
  - python setup.py build && python setup.py install
  - cd $TRAVIS_BUILD_DIR
  - pip install -r requirements.txt
  - python setup.py develop
  - cd tests/
  - ./get_test_data.sh
  - cd ..
  - py.test -vv tests/
